apiVersion: apps/v1
kind: Deployment
metadata:
  name: preceni-data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preceni-data
  template:
    metadata:
      labels:
        app: preceni-data
    spec:
      containers:
        - image: vidvidex/preceni-data:2023-11-04-13-10-00
          name: preceni-data
          env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-name
                key: db-name
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: database-host
                key: db-host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: database-port
                key: db-port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-user
                key: db-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-password
                key: db-password
          ports:
            - containerPort: 3000
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: preceni-data-lb
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: server
  selector:
    app: preceni-data